language: python

sudo: false

python:
  - "2.7"
  - "3.4"

install:
  - git clone https://github.com/evhub/coconut.git
  - pip install ./coconut

script:
  - coconut prisoner
  - python prisoner

notifications:
  email: false
